baseURL = "https://liaoshihang.com"
defaultContentLanguage = "en"
languageCode = "en"
title = "DrGoose"
theme = "dream"
[pagination]
pagerSize = 10
# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "img/global-background.jpg"
# backgroundImageDark = ""

author = "liaoshihang"
# description = ""
avatar = "img/avatar.png"
headerTitle = "DrGoose"
# motto = ""

# footerBottomText = ""

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "liaoshihang@gmail.com"

siteStartYear = 2025

favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
stickyNav = true
#noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
#reorderShares = ["x", "facebook", "whatsapp"]
[params.navItems]
reorderNavItems = ["about", "search", "rss", "posts", "categories", "tags"]
collapseNavItems = ["posts", "categories", "tags"]


# [params.twikoo]
# enabled = true
# envID = ""
# region = ""
# lang = ""

 [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

 [params.experimental]
 jsDate = true
 jsDateFormat = "yyyy年MM月dd日"
