baseURL = "https://liaoshihang.com"
defaultContentLanguage = "zh"
languageCode = "zh"
title = "Dr.Goose"
theme = "dream"

[languages]
[languages.zh]
title = "Dr.Goose"
languageName = "中文"
weight = 1

[languages.en]
title = "Dr.Goose"
languageName = "English"
weight = 2

[pagination]
pagerSize = 10

[params]
lightTheme = "emerald"
darkTheme = "forest"

author = "liaoshihang"
description = "打发时间的个人站"
avatar = "img/avatar.png"
headerTitle = "Dr.Goose"

rss = true

email = "liaoshihang@gmail.com"

siteStartYear = 2025

favicon = "favicon.ico"

# options
stickyNav = true
reorderNavItems = ["about","github", "search", "series"]
collapseNavItems = ["posts", "categories", "tags"]

showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true

[params.navItems]
github = { href = "https://github.com/stillhang", target = "_blank", icon = "logo-github", title = "GitHub" }

[params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"
